apiVersion: v1
kind: Service
metadata:
  name: cert-forge
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "seti.labels" . | nindent 4 }}
    app: cert-forge
spec:
  selector:
    app: cert-forge
  ports:
    - name: sign
      port: {{ .Values.certForge.port }}
      targetPort: {{ .Values.certForge.port }}
    - name: enrollment
      port: {{ .Values.certForge.enrollmentPort }}
      targetPort: {{ .Values.certForge.enrollmentPort }}
    - name: public
      port: {{ .Values.certForge.publicPort }}
      targetPort: {{ .Values.certForge.publicPort }}
