apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-forge
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vox.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-forge-secret-writer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vox.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-forge-secret-writer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vox.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: cert-forge
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: cert-forge-secret-writer
  apiGroup: rbac.authorization.k8s.io
