apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-store
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vox.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.resultsStore.storageClass }}
  storageClassName: {{ .Values.resultsStore.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.resultsStore.storage }}
