import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { useConstellation } from '../hooks/useConstellation';
import ConstellationNav from '../components/ConstellationNav';
import LaETab from '../components/LaETab';

const GATEWAY = import.meta.env.VITE_GATEWAY_URL || '';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface TestResult {
  request_id: string;
  service_name: string;
  test_name: string;
  passed: boolean;
  actual_status: number;
  expected_status: number;
  actual_response?: unknown;
  failure_reason?: string;
  latency_ms: number;
  executed_at: string;
}

interface ContractSuite {
  run_id: string;
  trigger: string;
  passed: number;
  failed: number;
  skipped: number;
  total: number;
  duration_ms: number;
  started_at: string;
  results?: TestResult[];
}

interface PlotRun {
  run_id: string;
  plot_id: string;
  plot_name: string;
  application_id: string;
  status: string;
  passed_steps: number;
  failed_steps: number;
  total_steps: number;
  started_at: string;
  steps?: Array<{
    step_number: number;
    description: string;
    passed: boolean;
    actual_status?: number;
    expected_status?: number;
    latency_ms?: number;
    failure_reason?: string;
  }>;
}

type ActiveTab = 'trial' | 'reports' | 'lae';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function triggerLabel(trigger: string): string {
  switch (trigger) {
    case 'startup':   return 'Startup';
    case 'scheduled': return 'Scheduled';
    case 'on-demand': return 'On-Demand';
    case 'ring':      return 'Ring (Trial)';
    default:          return trigger;
  }
}

function fmtDate(iso: string): string {
  try { return new Date(iso).toLocaleString(); } catch { return iso; }
}

function downloadContractReport(suite: ContractSuite) {
  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  const lines: string[] = [];
  lines.push('='.repeat(70));
  lines.push('  S.E.T.I. — CONTRACT TEST REPORT');
  lines.push(`  Generated: ${ts}`);
  lines.push(`  Run: ${suite.run_id}`);
  lines.push(`  Trigger: ${triggerLabel(suite.trigger)}  Started: ${fmtDate(suite.started_at)}`);
  lines.push(`  Summary: ${suite.passed}/${suite.total} passed, ${suite.failed} failed, ${suite.skipped} skipped  (${suite.duration_ms}ms)`);
  lines.push('='.repeat(70));
  lines.push('');
  for (const test of (suite.results || [])) {
    const isSkipped = test.failure_reason?.startsWith('skip:');
    const icon = isSkipped ? '—' : test.passed ? '✓' : '✗';
    lines.push(`${icon} ${test.test_name}  ${test.actual_status}/${test.expected_status}  ${test.latency_ms}ms`);
    if (!test.passed && test.failure_reason) {
      lines.push(`    Reason: ${test.failure_reason}`);
    }
    if (!test.passed && test.actual_response !== undefined) {
      lines.push(`    Response: ${JSON.stringify(test.actual_response)}`);
    }
  }
  lines.push('');
  lines.push(`Report generated by S.E.T.I. — Search for Erroneous Tessellated Interactions`);
  const now = new Date();
  const datePart = now.toISOString().slice(0, 10);
  const timePart = now.toTimeString().slice(0, 8).replace(/:/g, '-');
  downloadText(lines.join('\n'), `seti-contract-report-${datePart}-${timePart}.txt`);
}

function downloadPlotReport(run: PlotRun) {
  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  const lines: string[] = [];
  lines.push('='.repeat(70));
  lines.push('  S.E.T.I. — PLOT TEST REPORT');
  lines.push(`  Generated: ${ts}`);
  lines.push(`  Plot: ${run.plot_name || run.plot_id}`);
  lines.push(`  Run: ${run.run_id}  Started: ${fmtDate(run.started_at)}`);
  lines.push(`  Summary: ${run.passed_steps}/${run.total_steps} steps passed, ${run.failed_steps} failed`);
  lines.push(`  Status: ${run.status.toUpperCase()}`);
  lines.push('='.repeat(70));
  lines.push('');
  for (const step of (run.steps || [])) {
    const icon = step.passed ? '✓' : '✗';
    lines.push(`${icon} Step ${step.step_number}: ${step.description}`);
    lines.push(`    status: ${step.actual_status ?? '?'}/${step.expected_status ?? '?'}  latency: ${step.latency_ms ?? 0}ms`);
    if (!step.passed && step.failure_reason) {
      lines.push(`    reason: ${step.failure_reason}`);
    }
  }
  lines.push('');
  lines.push(`Report generated by S.E.T.I. — Search for Erroneous Tessellated Interactions`);
  const now = new Date();
  const datePart = now.toISOString().slice(0, 10);
  const timePart = now.toTimeString().slice(0, 8).replace(/:/g, '-');
  downloadText(lines.join('\n'), `seti-plot-report-${datePart}-${timePart}.txt`);
}

function downloadText(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Ring page
// ---------------------------------------------------------------------------

export default function Ring() {
  const { jwt, getFreshJWT, wranglerId, clearanceLevel, logout } = useAuth();
  const { active, constellations, setConstellation } = useConstellation(jwt);
  const [tab, setTab] = useState<ActiveTab>('trial');
  const isSecWrangler = clearanceLevel === 'sec-wr4ngler' || clearanceLevel === 'admin';

  return (
    <div style={s.root}>
      <div style={s.header}>
        <div style={s.headerLeft}>
          <span style={s.logo}>S.E.T.I.</span>
          <span style={s.pageBadge}>RING</span>
        </div>
        <div style={s.headerRight}>
          <Link to="/" style={s.navBtn}>{'<- Dashboard'}</Link>
          <Link to="/plots" style={s.navBtn}>Plots</Link>
          {isSecWrangler && <Link to="/admin" style={s.navBtnGold}>Admin</Link>}
          <span style={s.wranglerId}>{wranglerId}</span>
          <button style={s.logoutBtn} onClick={logout}>Sign out</button>
        </div>
      </div>

      <ConstellationNav constellations={constellations} active={active} onSelect={setConstellation} />

      <div style={s.ringTabs}>
        <button style={{ ...s.ringTab, ...(tab === 'trial' ? s.ringTabActive : {}) }}
          onClick={() => setTab('trial')}>Trial</button>
        <button style={{ ...s.ringTab, ...(tab === 'reports' ? s.ringTabActive : {}) }}
          onClick={() => setTab('reports')}>Reports</button>
        <button style={{ ...s.ringTab, ...(tab === 'lae' ? s.ringTabActive : {}) }}
          onClick={() => setTab('lae')}>LaE</button>
      </div>

      {tab === 'trial'
        ? <TrialTab isSecWrangler={isSecWrangler} getFreshJWT={getFreshJWT} />
        : tab === 'reports'
        ? <ReportsTab jwt={jwt} getFreshJWT={getFreshJWT} active={active} />
        : <LaETab jwt={jwt} getFreshJWT={getFreshJWT} />
      }
    </div>
  );
}

// ---------------------------------------------------------------------------
// Trial tab
// ---------------------------------------------------------------------------

function TrialTab({ isSecWrangler, getFreshJWT }: {
  isSecWrangler: boolean;
  getFreshJWT: () => Promise<string | null>;
}) {
  const [serviceName, setServiceName] = useState('');
  const [yaml, setYaml] = useState('');
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState<ContractSuite | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [expandedTest, setExpandedTest] = useState<string | null>(null);

  async function runTrial() {
    if (!serviceName.trim() || !yaml.trim()) return;
    setRunning(true); setResult(null); setError(null);
    try {
      const freshJwt = await getFreshJWT();
      if (!freshJwt) throw new Error('Session expired');
      const res = await fetch(`${GATEWAY}/augur-canis/ring/run`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${freshJwt}` },
        body: JSON.stringify({ service_name: serviceName.trim(), yaml: yaml.trim() }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.message || `HTTP ${res.status}`); return; }
      setResult(data);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Unknown error');
    } finally {
      setRunning(false);
    }
  }

  return (
    <div style={s.body}>
      <div style={s.intro}>
        <div style={s.introTitle}>TRIAL — AD-HOC CONTRACT TEST</div>
        <div style={s.introText}>
          Paste an OpenAPI contract YAML and specify the target Job. AC parses the
          endpoints and runs them over mTLS. Trial runs are recorded in Reports under
          "Ring (Trial)". Use this to verify a contract before it goes into the hardcoded
          suite, or to investigate a suspected regression without touching the code.
        </div>
        {!isSecWrangler && (
          <div style={s.accessDenied}>Trial requires sec-wr4ngler clearance.</div>
        )}
      </div>

      {isSecWrangler && (
        <>
          <div style={s.form}>
            <div style={s.formRow}>
              <div style={s.formGroup}>
                <label style={s.label}>TARGET JOB</label>
                <input
                  style={s.input}
                  placeholder="e.g. signal-clearance"
                  value={serviceName}
                  onChange={e => setServiceName(e.target.value)}
                  disabled={running}
                />
              </div>
              <button
                style={{ ...s.runBtn, opacity: running || !serviceName || !yaml ? 0.5 : 1 }}
                onClick={runTrial}
                disabled={running || !serviceName.trim() || !yaml.trim()}
              >
                {running ? 'Running...' : '> Run Trial'}
              </button>
            </div>
            <div style={s.formGroup}>
              <label style={s.label}>CONTRACT YAML</label>
              <textarea
                style={s.textarea}
                placeholder={`paths:\n  /health:\n    get:\n      summary: Health check\n  /auth/dev/login:\n    post:\n      summary: Dev login`}
                value={yaml}
                onChange={e => setYaml(e.target.value)}
                disabled={running}
                rows={16}
              />
            </div>
          </div>

          {error && (
            <div style={s.bannerErr}>
              <span>✗ {error}</span>
              <button style={s.bannerClose} onClick={() => setError(null)}>x</button>
            </div>
          )}

          {result && (
            <SuiteDetail suite={result} expandedTest={expandedTest} onToggle={setExpandedTest} />
          )}
        </>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Reports tab
// ---------------------------------------------------------------------------

function ReportsTab({ jwt, getFreshJWT, active }: {
  jwt: string | null;
  getFreshJWT: () => Promise<string | null>;
  active: { id: string; label: string };
}) {
  const [contractSuites, setContractSuites] = useState<ContractSuite[]>([]);
  const [plotRuns, setPlotRuns] = useState<PlotRun[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedContract, setSelectedContract] = useState('');
  const [selectedPlot, setSelectedPlot] = useState('');
  const [contractDetail, setContractDetail] = useState<ContractSuite | null>(null);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [expandedTest, setExpandedTest] = useState<string | null>(null);

  async function authFetch(path: string) {
    const freshJwt = await getFreshJWT();
    if (!freshJwt) throw new Error('Session expired');
    return fetch(`${GATEWAY}${path}`, {
      headers: { Authorization: `Bearer ${freshJwt}` },
    });
  }

  useEffect(() => {
    if (!jwt) return;
    setLoading(true);
    Promise.all([
      authFetch('/augur-canis/contract-suites'),
      authFetch(`/plot-results?application_id=${active.id}&limit=50`),
    ]).then(async ([csRes, prRes]) => {
      if (csRes.ok) { const d = await csRes.json(); setContractSuites(d.suites || []); }
      if (prRes.ok) { const d = await prRes.json(); setPlotRuns(d.runs || []); }
    }).finally(() => setLoading(false));
  }, [jwt, active.id]);

  async function selectContract(runId: string) {
    setSelectedContract(runId);
    setContractDetail(null);
    setExpandedTest(null);
    if (!runId) return;
    setLoadingDetail(true);
    try {
      // Try dedicated endpoint first; fall back to checks/recent for the latest run
      const res = await authFetch(`/augur-canis/contract-suites/${runId}`);
      if (res.ok) {
        setContractDetail(await res.json());
      } else {
        // Fallback: most recent
        const recent = await authFetch('/augur-canis/checks/recent');
        if (recent.ok) {
          const d = await recent.json();
          if (d.run_id === runId) setContractDetail(d);
        }
      }
    } finally {
      setLoadingDetail(false);
    }
  }

  const selectedPlotRun = plotRuns.find(r => r.run_id === selectedPlot) || null;

  return (
    <div style={s.body}>
      <div style={s.intro}>
        <div style={s.introTitle}>REPORTS</div>
        <div style={s.introText}>
          Historical contract and plot test results. Contract tests include scheduled
          runs, on-demand runs, and Ring trials. Plot tests are grouped by constellation.
        </div>
      </div>

      {loading ? <div style={s.empty}>Loading...</div> : (
        <div style={s.reportsCols}>

          {/* ---- Contract Tests ---- */}
          <div style={s.reportsGroup}>
            <div style={s.groupTitle}>CONTRACT TESTS</div>
            {contractSuites.length === 0
              ? <div style={s.empty}>No contract test runs yet.</div>
              : (
                <>
                  <select style={s.select} value={selectedContract}
                    onChange={e => selectContract(e.target.value)}>
                    <option value="">— select a run —</option>
                    {contractSuites.map(suite => (
                      <option key={suite.run_id} value={suite.run_id}>
                        {fmtDate(suite.started_at)} · {triggerLabel(suite.trigger)} · {suite.passed}/{suite.total}{suite.failed > 0 ? ` ✗${suite.failed}` : ' ✓'}
                      </option>
                    ))}
                  </select>

                  {loadingDetail && <div style={s.empty}>Loading detail...</div>}
                  {contractDetail && (
                    <>
                      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 6 }}>
                        <button style={s.dlBtn} onClick={() => downloadContractReport(contractDetail)}>
                          ↓ Download Report
                        </button>
                      </div>
                      <SuiteDetail suite={contractDetail} expandedTest={expandedTest} onToggle={setExpandedTest} />
                    </>
                  )}
                  {selectedContract && !loadingDetail && !contractDetail && (
                    <div style={s.empty}>Full detail stored in Redis. Only the most recent run is directly fetchable — earlier runs show summary only.</div>
                  )}
                </>
              )}
          </div>

          {/* ---- Plot Tests ---- */}
          <div style={s.reportsGroup}>
            <div style={s.groupTitle}>PLOT TESTS</div>
            {plotRuns.length === 0
              ? <div style={s.empty}>No plot test runs for {active.label}.</div>
              : (
                <>
                  <select style={s.select} value={selectedPlot}
                    onChange={e => setSelectedPlot(e.target.value)}>
                    <option value="">— select a run —</option>
                    {plotRuns.map(run => (
                      <option key={run.run_id} value={run.run_id}>
                        {fmtDate(run.started_at)} · {run.plot_name || run.plot_id} · {run.passed_steps}/{run.total_steps}{run.failed_steps > 0 ? ` ✗${run.failed_steps}` : ' ✓'}
                      </option>
                    ))}
                  </select>

                  {selectedPlotRun && (
                    <>
                      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 6 }}>
                        <button style={s.dlBtn} onClick={() => downloadPlotReport(selectedPlotRun)}>
                          ↓ Download Report
                        </button>
                      </div>
                      <div style={s.suiteDetail}>
                      <div style={s.suiteHeader}>
                        <span style={s.suiteTitle}>STEPS</span>
                        <span style={{
                          fontSize: 13, fontWeight: 600,
                          color: selectedPlotRun.status === 'passed' ? '#3fb950' : '#f85149',
                        }}>
                          {selectedPlotRun.status === 'passed' ? '✓' : '✗'} {selectedPlotRun.passed_steps}/{selectedPlotRun.total_steps}
                        </span>
                        <span style={{ fontSize: 11, color: '#484f58', flex: 1 }}>
                          {selectedPlotRun.plot_name || selectedPlotRun.plot_id}
                        </span>
                      </div>
                      <div style={s.testList}>
                        {(selectedPlotRun.steps || []).map(step => (
                          <div key={step.step_number}
                            style={{ ...s.testRow, borderLeftColor: step.passed ? '#3fb950' : '#f85149' }}>
                            <div style={{ ...s.testRowHeader, cursor: 'default' }}>
                              <span style={{ color: step.passed ? '#3fb950' : '#f85149', fontSize: 12 }}>
                                {step.passed ? '+' : 'x'}
                              </span>
                              <span style={s.testName}>Step {step.step_number}: {step.description}</span>
                              {step.actual_status !== undefined && (
                                <span style={s.testStatus}>{step.actual_status}/{step.expected_status}</span>
                              )}
                              {step.latency_ms !== undefined && (
                                <span style={s.testLatency}>{step.latency_ms}ms</span>
                              )}
                            </div>
                            {!step.passed && step.failure_reason && (
                              <div style={{ padding: '4px 10px 8px', fontSize: 11, color: '#f85149' }}>
                                {step.failure_reason}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                    </>
                  )}
                </>
              )}
          </div>

        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// SuiteDetail — shared between Trial results and Reports contract detail
// ---------------------------------------------------------------------------

function SuiteDetail({ suite, expandedTest, onToggle }: {
  suite: ContractSuite;
  expandedTest: string | null;
  onToggle: (id: string | null) => void;
}) {
  const results = suite.results || [];
  return (
    <div style={s.suiteDetail}>
      <div style={s.suiteHeader}>
        <span style={s.suiteTitle}>RESULTS</span>
        <span style={{ fontSize: 13, fontWeight: 600, color: suite.failed === 0 ? '#3fb950' : '#f85149' }}>
          {suite.failed === 0 ? '✓' : '✗'} {suite.passed}/{suite.total} passed
        </span>
        {suite.skipped > 0 && <span style={{ fontSize: 11, color: '#484f58' }}>{suite.skipped} skipped</span>}
        <span style={{ fontSize: 11, color: '#484f58' }}>{suite.duration_ms}ms</span>
        <span style={s.suiteRunId}>{(suite.run_id || '').slice(-16)}</span>
      </div>
      <div style={s.testList}>
        {results.map(test => {
          const isExpanded = expandedTest === test.request_id;
          const isSkipped = test.failure_reason?.startsWith('skip:');
          const color = isSkipped ? '#484f58' : test.passed ? '#3fb950' : '#f85149';
          const icon = isSkipped ? '—' : test.passed ? '+' : 'x';
          return (
            <div key={test.request_id} style={{ ...s.testRow, borderLeftColor: color }}>
              <div
                style={{ ...s.testRowHeader, cursor: !test.passed && !isSkipped ? 'pointer' : 'default' }}
                onClick={() => !test.passed && !isSkipped && onToggle(isExpanded ? null : test.request_id)}
              >
                <span style={{ color, fontSize: 12, flexShrink: 0 }}>{icon}</span>
                <span style={s.testName}>{test.test_name}</span>
                <span style={s.testStatus}>{test.actual_status}/{test.expected_status}</span>
                <span style={s.testLatency}>{test.latency_ms}ms</span>
                {!test.passed && !isSkipped && (
                  <span style={{ fontSize: 9, color: '#484f58' }}>{isExpanded ? '▲' : '▼'}</span>
                )}
              </div>
              {isExpanded && (
                <div style={s.testDetail}>
                  {test.failure_reason && (
                    <div style={s.detailRow}>
                      <span style={s.detailLabel}>Reason:</span>
                      <span style={{ color: '#f85149', fontSize: 11 }}>{test.failure_reason}</span>
                    </div>
                  )}
                  {test.actual_response !== undefined && (
                    <div style={s.detailRow}>
                      <span style={s.detailLabel}>Response:</span>
                      <pre style={s.detailPre}>{JSON.stringify(test.actual_response, null, 2)}</pre>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const s: Record<string, React.CSSProperties> = {
  root: { display: 'flex', flexDirection: 'column', minHeight: '100vh', background: '#0d1117', color: '#e6edf3', fontFamily: "'Segoe UI', system-ui, sans-serif" },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 20px', background: '#161b22', borderBottom: '1px solid #21262d' },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 16 },
  headerRight: { display: 'flex', alignItems: 'center', gap: 12 },
  logo: { fontSize: 16, fontWeight: 700, color: '#58a6ff', letterSpacing: 3 },
  pageBadge: { fontSize: 10, color: '#e3b341', border: '1px solid #e3b341', borderRadius: 4, padding: '2px 6px', letterSpacing: 1 },
  navBtn: { fontSize: 11, color: '#8b949e', textDecoration: 'none', border: '1px solid #30363d', borderRadius: 4, padding: '3px 10px' },
  navBtnGold: { fontSize: 11, color: '#e3b341', textDecoration: 'none', border: '1px solid #e3b341', borderRadius: 4, padding: '3px 10px' },
  wranglerId: { fontSize: 11, color: '#484f58' },
  logoutBtn: { background: 'none', border: '1px solid #30363d', borderRadius: 4, color: '#8b949e', fontSize: 11, cursor: 'pointer', padding: '4px 10px', fontFamily: 'inherit' },
  ringTabs: { display: 'flex', borderBottom: '1px solid #21262d', background: '#0d1117', padding: '0 32px' },
  ringTab: { background: 'none', border: 'none', borderBottom: '2px solid transparent', color: '#6e7681', fontSize: 12, cursor: 'pointer', padding: '10px 20px', fontFamily: 'inherit', letterSpacing: 0.5 },
  ringTabActive: { color: '#e6edf3', borderBottomColor: '#e3b341' },
  body: { padding: '24px 32px', maxWidth: 1200, margin: '0 auto', width: '100%' },
  intro: { marginBottom: 24 },
  introTitle: { fontSize: 11, color: '#484f58', letterSpacing: 2, marginBottom: 6 },
  introText: { fontSize: 12, color: '#6e7681', lineHeight: 1.7 },
  accessDenied: { marginTop: 12, fontSize: 12, color: '#f85149', border: '1px solid #f85149', borderRadius: 6, padding: '10px 16px' },
  empty: { fontSize: 12, color: '#484f58', padding: '16px 0', fontStyle: 'italic' },
  form: { display: 'flex', flexDirection: 'column', gap: 16, marginBottom: 20 },
  formRow: { display: 'flex', alignItems: 'flex-end', gap: 12 },
  formGroup: { display: 'flex', flexDirection: 'column', gap: 6, flex: 1 },
  label: { fontSize: 10, color: '#484f58', letterSpacing: 1 },
  input: { background: '#161b22', border: '1px solid #30363d', borderRadius: 6, color: '#e6edf3', fontSize: 12, padding: '8px 12px', fontFamily: 'inherit', outline: 'none' },
  textarea: { background: '#161b22', border: '1px solid #30363d', borderRadius: 6, color: '#e6edf3', fontSize: 11, padding: '10px 12px', fontFamily: "'Courier New', monospace", outline: 'none', resize: 'vertical' as const, lineHeight: 1.5 },
  runBtn: { background: '#388bfd26', border: '1px solid #1f6feb', borderRadius: 4, color: '#58a6ff', fontSize: 11, cursor: 'pointer', padding: '8px 18px', fontFamily: 'inherit', whiteSpace: 'nowrap' as const },
  bannerErr: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', border: '1px solid #f85149', borderRadius: 6, padding: '10px 16px', marginBottom: 16, fontSize: 12, color: '#f85149' },
  bannerClose: { background: 'none', border: 'none', cursor: 'pointer', fontSize: 14, color: 'inherit', fontFamily: 'inherit' },
  reportsCols: { display: 'flex', gap: 24, alignItems: 'flex-start' },
  reportsGroup: { flex: 1, minWidth: 0 },
  groupTitle: { fontSize: 10, color: '#484f58', letterSpacing: 2, marginBottom: 10 },
  select: { width: '100%', background: '#161b22', border: '1px solid #30363d', borderRadius: 6, color: '#e6edf3', fontSize: 11, padding: '8px 10px', fontFamily: 'inherit', outline: 'none', cursor: 'pointer', marginBottom: 8 },
  dlBtn: { background: 'none', border: '1px solid #30363d', borderRadius: 4, color: '#8b949e', fontSize: 11, cursor: 'pointer', padding: '4px 12px', fontFamily: 'inherit' },
  suiteDetail: { background: '#161b22', border: '1px solid #21262d', borderRadius: 8, overflow: 'hidden', marginTop: 8 },
  suiteHeader: { display: 'flex', alignItems: 'center', gap: 10, padding: '12px 14px', borderBottom: '1px solid #21262d' },
  suiteTitle: { fontSize: 10, color: '#484f58', letterSpacing: 2, flex: 1 },
  suiteRunId: { fontSize: 10, color: '#30363d', fontFamily: "'Courier New', monospace" },
  testList: { padding: '10px 12px', display: 'flex', flexDirection: 'column', gap: 4 },
  testRow: { borderLeft: '3px solid', borderTop: '1px solid #21262d', borderRight: '1px solid #21262d', borderBottom: '1px solid #21262d', borderRadius: '0 4px 4px 0', background: '#0d1117' },
  testRowHeader: { display: 'flex', alignItems: 'center', gap: 10, padding: '7px 10px' },
  testName: { fontSize: 11, color: '#c9d1d9', flex: 1, fontFamily: "'Courier New', monospace" },
  testStatus: { fontSize: 11, color: '#6e7681', fontFamily: "'Courier New', monospace" },
  testLatency: { fontSize: 11, color: '#484f58' },
  testDetail: { padding: '6px 10px 10px', borderTop: '1px solid #21262d' },
  detailRow: { display: 'flex', gap: 8, marginTop: 5, alignItems: 'flex-start' },
  detailLabel: { fontSize: 10, color: '#484f58', letterSpacing: 1, flexShrink: 0, marginTop: 2 },
  detailPre: { fontSize: 10, color: '#8b949e', background: '#161b22', border: '1px solid #21262d', borderRadius: 3, padding: '6px 8px', margin: 0, overflow: 'auto' as const, maxHeight: 180 },
};
